### ISSUE TITLE
package review issues

### ISSUE THREAD

**Issue by jpwrobinson** [renatoamorais/rfishprod#1]
Hi Renato - great work pulling this package together (I'm reviewing it for CR). Some problems however: 

- [x] objects db and repdata do not load into workspace. I downloaded separately from github to try the tutorial, but it would obviously be easier if you can call these directly from the package

- [x] R Studio crashes with a fatal error when I run predKmax. Presumably this is something to do with xgboost, which I'm not familiar with. Running this just in R returns error: 

```Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels```

- [x] Help file for predKmax is good, but it would help to have help for predM, applyVGBF, somaGain, somaLoss, applyMstoch

I'm using R 3.6.1.

Can you fix these issues? I'd like to run the full tutorial and see everything goes smoothly.

**Comment by renatoamorais** [comment]
Hi James, thanks for the report. The data objects should have gone straight into the workspace and help files for all functions should be there as well. I don't know what's the deal with xgboost though. I'll reproduce the errors in a naive system and try to figure out what's wrong. Thanks again!

**Comment by renatoamorais** [comment]
I hope the changes I made can fix these issues. Xgboost will require R 3.6.3, so I guess you will have to update your version. I have (now) managed to successfully run the code in 2 computers, both in R and R Studio. I will have 3 more people testing it tomorrow.

Other than that, all help files are in place and kicking, and I have added a little bit more info here and there.

**Comment by jpwrobinson** [comment]
excellent, fast work! I submitted my review - it mostly hinged on this package running ok. When you get the ms back, I'd just respond with the link to this thread. I'll try and test it again this week and let you know.

**Comment by renatoamorais** [comment]
Sounds good James, thanks. 

Just to summarise the results I got from running the package so far: it has been tested independently on 6 systems, by 5 people, with R versions 3.5.3, 3.6.3 and 4.0.0. All went smooth, with no errors. 

Use of an R version previous to 3.6.3 is contingent on pre-installed xgboost, as the current version of this package on CRAN requires R 3.6.3 as a minimum (as mentioned above). Please, let me know when you have done your test. Cheers!

**Comment by jpwrobinson** [comment]
Worked perfectly! Nice, no more issues from me. You could add the R version requirement to the readme - that rfishprod requires R 3.6.3 as minimum.

**Comment by renatoamorais** [comment]
Awesome! Yep, I guess I will add it as a requirement indeed. Thanks again.
